name: robo-cripto
type: container
builder: dockerfile
dockerfile: Dockerfile
port: 5000
env:
  - name: FLASK_APP
    value: api.py
  - name: FLASK_ENV
    value: production
  - name: PORT
    value: "5000"
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: PYTHONDONTWRITEBYTECODE
    value: "1"
  - name: PYTHONPATH
    value: "/app:/app/src"
volumes:
  - name: logs
    mountPath: /app/src/logs
  - name: db
    mountPath: /app/src/database.db 