version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=src.run_api
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PORT=5000
    volumes:
      - ./src/logs:/app/src/logs
      - ./src/database.db:/app/src/database.db
    restart: unless-stopped 