[phases.setup]
nixPkgs = [
    'python39',
    'gcc',
    'python39Packages.pip',
    'python39Packages.wheel',
    'python39Packages.setuptools'
]

[phases.install]
cmds = [
    'pip install --no-cache-dir --upgrade pip setuptools wheel',
    'pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT src.run_api:app' 